# Generated by Django 3.2 on 2021-04-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='start_date',
        ),
    ]
